DEBUG 2019-07-16 16:05:38,667: 	 Executing command: 'submit'
DEBUG 2019-07-16 16:05:38,677: 	 Found CRAB cache file /afs/cern.ch/user/v/vshang/.crab3
DEBUG 2019-07-16 16:05:38,687: 	 Checking credentials
DEBUG 2019-07-16 16:05:38,687: 	 Found proxy file /tmp/x509up_u120824
DEBUG 2019-07-16 16:05:38,687: 	 Getting proxy life time left
DEBUG 2019-07-16 16:05:39,394: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u120824 -timeleft
 output : 604764

 error: 
 retcode : 0
DEBUG 2019-07-16 16:05:40,103: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u120824 -actimeleft
 output : 604763

 error: 
 retcode : 0
DEBUG 2019-07-16 16:05:40,103: 	 Proxy lifetime 604764 secs is different from voms extension lifetime 604763 secs for proxy: /tmp/x509up_u120824
DEBUG 2019-07-16 16:05:40,104: 	 Proxy valid for 167:59:23 hours
DEBUG 2019-07-16 16:05:40,104: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
DEBUG 2019-07-16 16:05:40,113: 	 Executing command: 'submit'
DEBUG 2019-07-16 16:05:40,113: 	 Found CRAB cache file /afs/cern.ch/user/v/vshang/.crab3
DEBUG 2019-07-16 16:05:40,120: 	 Checking credentials
DEBUG 2019-07-16 16:05:40,121: 	 Found proxy file /tmp/x509up_u120824
DEBUG 2019-07-16 16:05:40,121: 	 Getting proxy life time left
DEBUG 2019-07-16 16:05:40,825: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u120824 -timeleft
 output : 604763

 error: 
 retcode : 0
DEBUG 2019-07-16 16:05:41,530: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u120824 -actimeleft
 output : 604762

 error: 
 retcode : 0
DEBUG 2019-07-16 16:05:41,530: 	 Proxy lifetime 604763 secs is different from voms extension lifetime 604762 secs for proxy: /tmp/x509up_u120824
DEBUG 2019-07-16 16:05:41,530: 	 Proxy valid for 167:59:22 hours
DEBUG 2019-07-16 16:05:41,531: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
DEBUG 2019-07-17 14:49:19,542: 	 Executing command: 'submit'
DEBUG 2019-07-17 14:49:19,557: 	 Found CRAB cache file /afs/cern.ch/user/v/vshang/.crab3
DEBUG 2019-07-17 14:49:19,581: 	 Checking credentials
DEBUG 2019-07-17 14:49:19,581: 	 Found proxy file /tmp/x509up_u120824
DEBUG 2019-07-17 14:49:19,581: 	 Getting proxy life time left
DEBUG 2019-07-17 14:49:20,286: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u120824 -timeleft
 output : 604755

 error: 
 retcode : 0
DEBUG 2019-07-17 14:49:21,095: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u120824 -actimeleft
 output : 604754

 error: 
 retcode : 0
DEBUG 2019-07-17 14:49:21,096: 	 Proxy lifetime 604755 secs is different from voms extension lifetime 604754 secs for proxy: /tmp/x509up_u120824
DEBUG 2019-07-17 14:49:21,096: 	 Proxy valid for 167:59:14 hours
DEBUG 2019-07-17 14:49:21,096: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
DEBUG 2019-07-17 14:49:21,127: 	 Executing command: 'submit'
DEBUG 2019-07-17 14:49:21,127: 	 Found CRAB cache file /afs/cern.ch/user/v/vshang/.crab3
DEBUG 2019-07-17 14:49:21,136: 	 Checking credentials
DEBUG 2019-07-17 14:49:21,136: 	 Found proxy file /tmp/x509up_u120824
DEBUG 2019-07-17 14:49:21,136: 	 Getting proxy life time left
DEBUG 2019-07-17 14:49:21,941: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u120824 -timeleft
 output : 604754

 error: 
 retcode : 0
DEBUG 2019-07-17 14:49:22,647: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u120824 -actimeleft
 output : 604753

 error: 
 retcode : 0
DEBUG 2019-07-17 14:49:22,647: 	 Proxy lifetime 604754 secs is different from voms extension lifetime 604753 secs for proxy: /tmp/x509up_u120824
DEBUG 2019-07-17 14:49:22,647: 	 Proxy valid for 167:59:13 hours
DEBUG 2019-07-17 14:49:22,648: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
DEBUG 2019-07-19 14:47:37,721: 	 Executing command: 'submit'
DEBUG 2019-07-19 14:47:37,727: 	 Found CRAB cache file /afs/cern.ch/user/v/vshang/.crab3
DEBUG 2019-07-19 14:47:37,733: 	 Checking credentials
DEBUG 2019-07-19 14:47:37,733: 	 Found proxy file /tmp/x509up_u120824
DEBUG 2019-07-19 14:47:37,733: 	 Getting proxy life time left
DEBUG 2019-07-19 14:47:38,337: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u120824 -timeleft
 output : 604794

 error: 
 retcode : 0
DEBUG 2019-07-19 14:47:38,941: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u120824 -actimeleft
 output : 604794

 error: 
 retcode : 0
DEBUG 2019-07-19 14:47:38,941: 	 Proxy valid for 167:59:54 hours
DEBUG 2019-07-19 14:47:38,942: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
DEBUG 2019-07-19 14:47:38,965: 	 Executing command: 'submit'
DEBUG 2019-07-19 14:47:38,966: 	 Found CRAB cache file /afs/cern.ch/user/v/vshang/.crab3
DEBUG 2019-07-19 14:47:38,972: 	 Checking credentials
DEBUG 2019-07-19 14:47:38,972: 	 Found proxy file /tmp/x509up_u120824
DEBUG 2019-07-19 14:47:38,972: 	 Getting proxy life time left
DEBUG 2019-07-19 14:47:39,586: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u120824 -timeleft
 output : 604793

 error: 
 retcode : 0
DEBUG 2019-07-19 14:47:40,191: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u120824 -actimeleft
 output : 604792

 error: 
 retcode : 0
DEBUG 2019-07-19 14:47:40,191: 	 Proxy lifetime 604793 secs is different from voms extension lifetime 604792 secs for proxy: /tmp/x509up_u120824
DEBUG 2019-07-19 14:47:40,191: 	 Proxy valid for 167:59:52 hours
DEBUG 2019-07-19 14:47:40,191: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
DEBUG 2019-07-25 12:08:13,200: 	 Executing command: 'resubmit'
DEBUG 2019-07-25 12:08:13,200: 	 Found CRAB cache file /afs/cern.ch/user/v/vshang/.crab3
DEBUG 2019-07-26 10:59:26,413: 	 Executing command: 'submit'
DEBUG 2019-07-26 10:59:26,418: 	 Found CRAB cache file /afs/cern.ch/user/v/vshang/.crab3
DEBUG 2019-07-26 10:59:26,427: 	 Checking credentials
DEBUG 2019-07-26 10:59:26,427: 	 Found proxy file /tmp/x509up_u120824
DEBUG 2019-07-26 10:59:26,427: 	 Getting proxy life time left
DEBUG 2019-07-26 10:59:26,530: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u120824 -timeleft
 output : 604222

 error: 
 retcode : 0
DEBUG 2019-07-26 10:59:26,634: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u120824 -actimeleft
 output : 604222

 error: 
 retcode : 0
DEBUG 2019-07-26 10:59:26,634: 	 Proxy valid for 167:50:22 hours
DEBUG 2019-07-26 10:59:26,635: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
DEBUG 2019-07-26 11:06:19,050: 	 Executing command: 'submit'
DEBUG 2019-07-26 11:06:19,056: 	 Found CRAB cache file /afs/cern.ch/user/v/vshang/.crab3
DEBUG 2019-07-26 11:06:19,066: 	 Checking credentials
DEBUG 2019-07-26 11:06:19,066: 	 Found proxy file /tmp/x509up_u120824
DEBUG 2019-07-26 11:06:19,066: 	 Getting proxy life time left
DEBUG 2019-07-26 11:06:19,169: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u120824 -timeleft
 output : 43068

 error: 
 retcode : 0
DEBUG 2019-07-26 11:06:19,273: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u120824 -actimeleft
 output : 43068

 error: 
 retcode : 0
DEBUG 2019-07-26 11:06:19,273: 	 Proxy valid for 11:57:48 hours
DEBUG 2019-07-26 11:06:19,274: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
DEBUG 2019-08-07 11:54:33,179: 	 Executing command: 'submit'
DEBUG 2019-08-07 11:54:33,187: 	 Found CRAB cache file /afs/cern.ch/user/v/vshang/.crab3
DEBUG 2019-08-07 11:54:33,198: 	 Checking credentials
DEBUG 2019-08-07 11:54:33,198: 	 Found proxy file /tmp/x509up_u120824
DEBUG 2019-08-07 11:54:33,198: 	 Getting proxy life time left
DEBUG 2019-08-07 11:54:33,303: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u120824 -timeleft
 output : 42958

 error: 
 retcode : 0
DEBUG 2019-08-07 11:54:33,407: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u120824 -actimeleft
 output : 42958

 error: 
 retcode : 0
DEBUG 2019-08-07 11:54:33,407: 	 Proxy valid for 11:55:58 hours
DEBUG 2019-08-07 11:54:33,408: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
DEBUG 2022-12-06 13:48:16.082 UTC: 	 CRAB Client version: v3.221018
DEBUG 2022-12-06 13:48:16.083 UTC: 	 Running on: Linux login01.hep.wisc.edu 5.4.217-1.el7.elrepo.x86_64 #1 SMP Thu Oct 6 13:02:21 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-12-06 13:48:16.083 UTC: 	 Executing command: 'submit'
DEBUG 2022-12-06 13:48:16.084 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
INFO 2022-12-06 13:48:16.087 UTC: 	 Will use CRAB configuration file r1_submit_crab.py
DEBUG 2022-12-06 13:48:16.088 UTC: 	 Loading CRAB configuration file.
ERROR 2022-12-06 13:48:16.092 UTC: 	 Error while loading CRAB configuration:
invalid syntax (r1_submit_crab.py, line 50)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2022-12-06 13:48:16.093 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/WMCore/Configuration.py", line 326, in loadConfigurationFile
    modRef = imp.load_module(cfgBaseName, modPath[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_3_0_pre4/src/L1Trigger/L1EGRateStudies/test/crab/r1_submit_crab.py", line 50
    print "Failed submitting task: %s" % (hte.headers)
          ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 55, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/WMCore/Configuration.py", line 334, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_3_0_pre4/src/L1Trigger/L1EGRateStudies/test/crab/r1_submit_crab.py
Due to error:
invalid syntax (r1_submit_crab.py, line 50)Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/WMCore/Configuration.py", line 326, in loadConfigurationFile
    modRef = imp.load_module(cfgBaseName, modPath[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_3_0_pre4/src/L1Trigger/L1EGRateStudies/test/crab/r1_submit_crab.py", line 50
    print "Failed submitting task: %s" % (hte.headers)
          ^
SyntaxError: invalid syntax


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 89, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
invalid syntax (r1_submit_crab.py, line 50)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2022-12-06 13:48:16.112 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_3_0_pre4/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2022-12-06 13:49:50.114 UTC: 	 CRAB Client version: v3.221018
DEBUG 2022-12-06 13:49:50.114 UTC: 	 Running on: Linux login01.hep.wisc.edu 5.4.217-1.el7.elrepo.x86_64 #1 SMP Thu Oct 6 13:02:21 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-12-06 13:49:50.114 UTC: 	 Executing command: 'submit'
DEBUG 2022-12-06 13:49:50.115 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
INFO 2022-12-06 13:49:50.119 UTC: 	 Will use CRAB configuration file r1_submit_crab.py
DEBUG 2022-12-06 13:49:50.119 UTC: 	 Loading CRAB configuration file.
ERROR 2022-12-06 13:49:50.127 UTC: 	 Error while loading CRAB configuration:
Missing parentheses in call to 'print'. Did you mean print("Base: ",base)? (r1_submit_crab.py, line 58)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2022-12-06 13:49:50.127 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/WMCore/Configuration.py", line 326, in loadConfigurationFile
    modRef = imp.load_module(cfgBaseName, modPath[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_3_0_pre4/src/L1Trigger/L1EGRateStudies/test/crab/r1_submit_crab.py", line 58
    print "Base: ",base
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Base: ",base)?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 55, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/WMCore/Configuration.py", line 334, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_3_0_pre4/src/L1Trigger/L1EGRateStudies/test/crab/r1_submit_crab.py
Due to error:
Missing parentheses in call to 'print'. Did you mean print("Base: ",base)? (r1_submit_crab.py, line 58)Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/WMCore/Configuration.py", line 326, in loadConfigurationFile
    modRef = imp.load_module(cfgBaseName, modPath[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_3_0_pre4/src/L1Trigger/L1EGRateStudies/test/crab/r1_submit_crab.py", line 58
    print "Base: ",base
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Base: ",base)?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 89, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
Missing parentheses in call to 'print'. Did you mean print("Base: ",base)? (r1_submit_crab.py, line 58)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2022-12-06 13:49:50.130 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_3_0_pre4/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2022-12-06 13:51:59.802 UTC: 	 CRAB Client version: v3.221018
DEBUG 2022-12-06 13:51:59.803 UTC: 	 Running on: Linux login01.hep.wisc.edu 5.4.217-1.el7.elrepo.x86_64 #1 SMP Thu Oct 6 13:02:21 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-12-06 13:51:59.803 UTC: 	 Executing command: 'submit'
DEBUG 2022-12-06 13:51:59.803 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
INFO 2022-12-06 13:51:59.810 UTC: 	 Will use CRAB configuration file r1_submit_crab.py
DEBUG 2022-12-06 13:51:59.810 UTC: 	 Loading CRAB configuration file.
ERROR 2022-12-06 13:51:59.826 UTC: 	 Error while loading CRAB configuration:
invalid syntax (r1_submit_crab.py, line 50)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2022-12-06 13:51:59.826 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/WMCore/Configuration.py", line 326, in loadConfigurationFile
    modRef = imp.load_module(cfgBaseName, modPath[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_3_0_pre4/src/L1Trigger/L1EGRateStudies/test/crab/r1_submit_crab.py", line 50
    print "Failed submitting task: %s" % (hte.headers)
          ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 55, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/WMCore/Configuration.py", line 334, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_3_0_pre4/src/L1Trigger/L1EGRateStudies/test/crab/r1_submit_crab.py
Due to error:
invalid syntax (r1_submit_crab.py, line 50)Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/WMCore/Configuration.py", line 326, in loadConfigurationFile
    modRef = imp.load_module(cfgBaseName, modPath[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_3_0_pre4/src/L1Trigger/L1EGRateStudies/test/crab/r1_submit_crab.py", line 50
    print "Failed submitting task: %s" % (hte.headers)
          ^
SyntaxError: invalid syntax


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 89, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
invalid syntax (r1_submit_crab.py, line 50)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2022-12-06 13:51:59.833 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_3_0_pre4/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2022-12-06 13:58:32.862 UTC: 	 CRAB Client version: v3.221018
DEBUG 2022-12-06 13:58:32.862 UTC: 	 Running on: Linux login01.hep.wisc.edu 5.4.217-1.el7.elrepo.x86_64 #1 SMP Thu Oct 6 13:02:21 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-12-06 13:58:32.862 UTC: 	 Executing command: 'submit'
DEBUG 2022-12-06 13:58:32.863 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
INFO 2022-12-06 13:58:32.868 UTC: 	 Will use CRAB configuration file r1_submit_crab.py
DEBUG 2022-12-06 13:58:32.868 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-12-06 13:58:33.005 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-12-06 13:58:33.006 UTC: 	 Working area '/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_3_0_pre4/src/L1Trigger/L1EGRateStudies/test/crab/crab_20221206_VBFHTT-PU200_r1_CMSSW_12_3_0_pre4' already exists 
Please change the requestName in the config file
ERROR 2022-12-06 13:58:33.006 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_3_0_pre4/src/L1Trigger/L1EGRateStudies/test/crab/crab_20221206_VBFHTT-PU200_r1_CMSSW_12_3_0_pre4' already exists 
Please change the requestName in the config file
INFO 2022-12-06 13:58:33.012 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_3_0_pre4/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2023-05-04 07:44:22.383 UTC: 	 CRAB Client version: v3.230417
DEBUG 2023-05-04 07:44:22.383 UTC: 	 Running on: Linux login06.hep.wisc.edu 5.4.236-1.el7.elrepo.x86_64 #1 SMP Mon Mar 13 21:36:53 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-05-04 07:44:22.383 UTC: 	 Executing command: 'submit'
DEBUG 2023-05-04 07:44:22.383 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
INFO 2023-05-04 07:44:22.384 UTC: 	 Will use CRAB configuration file r1_crabby_jets.py
DEBUG 2023-05-04 07:44:22.384 UTC: 	 Loading CRAB configuration file.
ERROR 2023-05-04 07:44:46.900 UTC: 	 Error while loading CRAB configuration:
Unable to find a Configuration object instance in file:
/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/r1_crabby_jets.py

Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2023-05-04 07:44:46.900 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 55, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/WMCore/Configuration.py", line 342, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to find a Configuration object instance in file:
/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/r1_crabby_jets.py


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 89, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
Unable to find a Configuration object instance in file:
/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/r1_crabby_jets.py

Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2023-05-04 07:44:46.913 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2023-05-11 15:35:05.508 UTC: 	 CRAB Client version: v3.230417
DEBUG 2023-05-11 15:35:05.508 UTC: 	 Running on: Linux login06.hep.wisc.edu 5.4.236-1.el7.elrepo.x86_64 #1 SMP Mon Mar 13 21:36:53 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-05-11 15:35:05.509 UTC: 	 Executing command: 'kill'
DEBUG 2023-05-11 15:35:05.509 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
ERROR 2023-05-11 15:35:05.510 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/crab_20230511_minBias-PU200_v27_r1_CMSSW_12_5_2_patch1
ERROR 2023-05-11 15:35:05.510 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 508, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 502, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/ClientUtilities.py", line 440, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/crab_20230511_minBias-PU200_v27_r1_CMSSW_12_5_2_patch1
INFO 2023-05-11 15:35:05.538 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2023-05-11 15:37:25.430 UTC: 	 CRAB Client version: v3.230417
DEBUG 2023-05-11 15:37:25.430 UTC: 	 Running on: Linux login06.hep.wisc.edu 5.4.236-1.el7.elrepo.x86_64 #1 SMP Mon Mar 13 21:36:53 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-05-11 15:37:25.430 UTC: 	 Executing command: 'status'
DEBUG 2023-05-11 15:37:25.430 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
ERROR 2023-05-11 15:37:25.432 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/crab_20230511_minBias-PU200_v27_r1_CMSSW_12_5_2_patch1
ERROR 2023-05-11 15:37:25.432 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 508, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 502, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/ClientUtilities.py", line 440, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/crab_20230511_minBias-PU200_v27_r1_CMSSW_12_5_2_patch1
INFO 2023-05-11 15:37:25.436 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2023-05-11 16:37:05.860 UTC: 	 CRAB Client version: v3.230417
DEBUG 2023-05-11 16:37:05.860 UTC: 	 Running on: Linux login06.hep.wisc.edu 5.4.236-1.el7.elrepo.x86_64 #1 SMP Mon Mar 13 21:36:53 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-05-11 16:37:05.860 UTC: 	 Executing command: 'status'
DEBUG 2023-05-11 16:37:05.862 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
ERROR 2023-05-11 16:37:05.867 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/crab_20230511_minBias-PU200_v27_r1_CMSSW_12_5_2_patch1
ERROR 2023-05-11 16:37:05.867 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 508, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 502, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/ClientUtilities.py", line 440, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/crab_20230511_minBias-PU200_v27_r1_CMSSW_12_5_2_patch1
INFO 2023-05-11 16:37:05.877 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2023-06-01 15:38:10.868 UTC: 	 CRAB Client version: v3.230417
DEBUG 2023-06-01 15:38:10.869 UTC: 	 Running on: Linux login01.hep.wisc.edu 5.4.217-1.el7.elrepo.x86_64 #1 SMP Thu Oct 6 13:02:21 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-06-01 15:38:10.869 UTC: 	 Executing command: 'submit'
DEBUG 2023-06-01 15:38:10.870 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
INFO 2023-06-01 15:38:10.872 UTC: 	 Will use CRAB configuration file r1_submit_crab.py
DEBUG 2023-06-01 15:38:10.873 UTC: 	 Loading CRAB configuration file.
DEBUG 2023-06-01 15:38:10.876 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2023-06-01 15:38:10.877 UTC: 	 Working area '/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/crab_20230601_QCD-PU200_v27_r1_CMSSW_12_5_2_patch1_PallabiJets' already exists 
Please change the requestName in the config file
ERROR 2023-06-01 15:38:10.877 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/crab_20230601_QCD-PU200_v27_r1_CMSSW_12_5_2_patch1_PallabiJets' already exists 
Please change the requestName in the config file
INFO 2023-06-01 15:38:10.922 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2023-07-10 15:01:50.929 UTC: 	 CRAB Client version: v3.230417
DEBUG 2023-07-10 15:01:50.930 UTC: 	 Running on: Linux login06.hep.wisc.edu 5.4.246-1.el7.elrepo.x86_64 #1 SMP Fri Jun 9 14:57:29 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-07-10 15:01:50.930 UTC: 	 Executing command: 'status'
DEBUG 2023-07-10 15:01:50.931 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
ERROR 2023-07-10 15:01:50.933 UTC: 	 Error: crab_20230709_VBFHTT-PU200_v27_r1_CMSSW_12_5_2_patch1_PallabiJets_tau is not a valid CRAB project directory.
ERROR 2023-07-10 15:01:50.934 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.01/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.01/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_20230709_VBFHTT-PU200_v27_r1_CMSSW_12_5_2_patch1_PallabiJets_tau is not a valid CRAB project directory.
INFO 2023-07-10 15:01:50.960 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2023-08-24 02:16:22.344 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-08-24 02:16:22.345 UTC: 	 Running on: Linux login01.hep.wisc.edu 5.4.246-1.el7.elrepo.x86_64 #1 SMP Fri Jun 9 14:57:29 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-08-24 02:16:22.345 UTC: 	 Executing command: 'status'
DEBUG 2023-08-24 02:16:22.346 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
ERROR 2023-08-24 02:16:22.348 UTC: 	 Error: crab_20230808_VBFHTT-PU200_v27_r1_CMSSW_12_5_2_patch1_GCTTaus_3 is not a valid CRAB project directory.
ERROR 2023-08-24 02:16:22.348 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_20230808_VBFHTT-PU200_v27_r1_CMSSW_12_5_2_patch1_GCTTaus_3 is not a valid CRAB project directory.
INFO 2023-08-24 02:16:22.382 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2023-09-13 13:19:19.629 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-09-13 13:19:19.630 UTC: 	 Running on: Linux login01.hep.wisc.edu 5.4.246-1.el7.elrepo.x86_64 #1 SMP Fri Jun 9 14:57:29 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-09-13 13:19:19.630 UTC: 	 Executing command: 'submit'
DEBUG 2023-09-13 13:19:19.632 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
INFO 2023-09-13 13:19:19.637 UTC: 	 Will use CRAB configuration file r1_submit_crab.py
DEBUG 2023-09-13 13:19:19.637 UTC: 	 Loading CRAB configuration file.
DEBUG 2023-09-13 13:19:19.683 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2023-09-13 13:19:19.684 UTC: 	 Working area '/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/crab_20230808_VBFHTT-PU200_v27_r1_CMSSW_12_5_2_patch1_GCTTaus_Cross' already exists 
Please change the requestName in the config file
ERROR 2023-09-13 13:19:19.685 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/crab_20230808_VBFHTT-PU200_v27_r1_CMSSW_12_5_2_patch1_GCTTaus_Cross' already exists 
Please change the requestName in the config file
INFO 2023-09-13 13:19:19.708 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_12_5_2_patch1/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2023-11-01 16:36:35.522 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-11-01 16:36:35.522 UTC: 	 Running on: Linux login01.hep.wisc.edu 5.4.256-1.el7.elrepo.x86_64 #1 SMP Sat Sep 2 23:00:29 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-11-01 16:36:35.522 UTC: 	 Executing command: 'status'
DEBUG 2023-11-01 16:36:35.523 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
ERROR 2023-11-01 16:36:35.524 UTC: 	 Error: crab_20230101_minBias-PU200_v27_r1_CMSSW_13_2_0_GCTJe is not a valid CRAB project directory.
ERROR 2023-11-01 16:36:35.524 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_20230101_minBias-PU200_v27_r1_CMSSW_13_2_0_GCTJe is not a valid CRAB project directory.
INFO 2023-11-01 16:36:35.528 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_13_2_0/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2023-11-14 08:10:01.884 UTC: 	 CRAB Client version: v3.231010
DEBUG 2023-11-14 08:10:01.885 UTC: 	 Running on: Linux login05.hep.wisc.edu 5.4.256-1.el7.elrepo.x86_64 #1 SMP Sat Sep 2 23:00:29 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-11-14 08:10:01.885 UTC: 	 Executing command: 'submit'
DEBUG 2023-11-14 08:10:01.885 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
INFO 2023-11-14 08:10:01.887 UTC: 	 Will use CRAB configuration file r1_submit_crab.py
DEBUG 2023-11-14 08:10:01.887 UTC: 	 Loading CRAB configuration file.
DEBUG 2023-11-14 08:10:01.889 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2023-11-14 08:10:01.890 UTC: 	 Working area '/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_13_2_0/src/L1Trigger/L1EGRateStudies/test/crab/crab_20231108_QCD-PU200_v27_r1_CMSSW_13_2_0_GCTJetsWithHoe_fixedv2' already exists 
Please change the requestName in the config file
ERROR 2023-11-14 08:10:01.890 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_13_2_0/src/L1Trigger/L1EGRateStudies/test/crab/crab_20231108_QCD-PU200_v27_r1_CMSSW_13_2_0_GCTJetsWithHoe_fixedv2' already exists 
Please change the requestName in the config file
INFO 2023-11-14 08:10:01.909 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_13_2_0/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2023-11-21 03:22:25.708 UTC: 	 CRAB Client version: v3.231010
DEBUG 2023-11-21 03:22:25.709 UTC: 	 Running on: Linux login05.hep.wisc.edu 5.4.256-1.el7.elrepo.x86_64 #1 SMP Sat Sep 2 23:00:29 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-11-21 03:22:25.709 UTC: 	 Executing command: 'status'
DEBUG 2023-11-21 03:22:25.711 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
ERROR 2023-11-21 03:22:25.716 UTC: 	 Error: crab_20231116_QCD-PU200_v27_r1_CMSSW_13_2_0_GCTJetsWithHoe_fixed3 is not a valid CRAB project directory.
ERROR 2023-11-21 03:22:25.717 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/SubCommand.py", line 277, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/SubCommand.py", line 644, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_20231116_QCD-PU200_v27_r1_CMSSW_13_2_0_GCTJetsWithHoe_fixed3 is not a valid CRAB project directory.
INFO 2023-11-21 03:22:25.766 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_13_2_0/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2023-11-29 11:39:09.596 UTC: 	 CRAB Client version: v3.231010
DEBUG 2023-11-29 11:39:09.596 UTC: 	 Running on: Linux login05.hep.wisc.edu 5.4.256-1.el7.elrepo.x86_64 #1 SMP Sat Sep 2 23:00:29 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-11-29 11:39:09.597 UTC: 	 Executing command: 'submit'
DEBUG 2023-11-29 11:39:09.597 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
INFO 2023-11-29 11:39:09.598 UTC: 	 Will use CRAB configuration file r1_submit_crab.py
DEBUG 2023-11-29 11:39:09.598 UTC: 	 Loading CRAB configuration file.
DEBUG 2023-11-29 11:39:09.599 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2023-11-29 11:39:09.600 UTC: 	 Working area '/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_13_2_0/src/L1Trigger/L1EGRateStudies/test/crab/crab_20231129_QCD-PU200_v27_r1_CMSSW_13_2_0_GCTJetsWithHoe' already exists 
Please change the requestName in the config file
ERROR 2023-11-29 11:39:09.600 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_13_2_0/src/L1Trigger/L1EGRateStudies/test/crab/crab_20231129_QCD-PU200_v27_r1_CMSSW_13_2_0_GCTJetsWithHoe' already exists 
Please change the requestName in the config file
INFO 2023-11-29 11:39:09.655 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_13_2_0/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2023-12-05 17:09:16.565 UTC: 	 CRAB Client version: v3.231010
DEBUG 2023-12-05 17:09:16.565 UTC: 	 Running on: Linux login05.hep.wisc.edu 5.4.261-1.el7.elrepo.x86_64 #1 SMP Mon Nov 20 15:11:45 EST 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-12-05 17:09:16.565 UTC: 	 Executing command: 'submit'
DEBUG 2023-12-05 17:09:16.566 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
INFO 2023-12-05 17:09:16.567 UTC: 	 Will use CRAB configuration file r1_submit_crab.py
DEBUG 2023-12-05 17:09:16.567 UTC: 	 Loading CRAB configuration file.
DEBUG 2023-12-05 17:09:16.574 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2023-12-05 17:09:16.575 UTC: 	 Working area '/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_13_2_0/src/L1Trigger/L1EGRateStudies/test/crab/crab_20231203_minBias-PU200_v27_r1_CMSSW_13_2_0_GCTJetsWithHoev2' already exists 
Please change the requestName in the config file
ERROR 2023-12-05 17:09:16.575 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_13_2_0/src/L1Trigger/L1EGRateStudies/test/crab/crab_20231203_minBias-PU200_v27_r1_CMSSW_13_2_0_GCTJetsWithHoev2' already exists 
Please change the requestName in the config file
INFO 2023-12-05 17:09:16.607 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_13_2_0/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2023-12-05 17:31:34.843 UTC: 	 CRAB Client version: v3.231010
DEBUG 2023-12-05 17:31:34.844 UTC: 	 Running on: Linux login05.hep.wisc.edu 5.4.261-1.el7.elrepo.x86_64 #1 SMP Mon Nov 20 15:11:45 EST 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-12-05 17:31:34.844 UTC: 	 Executing command: 'status'
DEBUG 2023-12-05 17:31:34.844 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
ERROR 2023-12-05 17:31:34.845 UTC: 	 Error: crab_20231203_VBFHTT-PU200_ is not a valid CRAB project directory.
ERROR 2023-12-05 17:31:34.845 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/SubCommand.py", line 277, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/SubCommand.py", line 644, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_20231203_VBFHTT-PU200_ is not a valid CRAB project directory.
INFO 2023-12-05 17:31:34.848 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_13_2_0/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2023-12-06 16:01:50.537 UTC: 	 CRAB Client version: v3.231010
DEBUG 2023-12-06 16:01:50.538 UTC: 	 Running on: Linux login05.hep.wisc.edu 5.4.261-1.el7.elrepo.x86_64 #1 SMP Mon Nov 20 15:11:45 EST 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-12-06 16:01:50.538 UTC: 	 Executing command: 'status'
DEBUG 2023-12-06 16:01:50.538 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
ERROR 2023-12-06 16:01:50.539 UTC: 	 Error: crab_20231203_Min is not a valid CRAB project directory.
ERROR 2023-12-06 16:01:50.539 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/SubCommand.py", line 277, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.231010.00/lib/CRABClient/Commands/SubCommand.py", line 644, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_20231203_Min is not a valid CRAB project directory.
INFO 2023-12-06 16:01:50.542 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_13_2_0/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2024-02-21 13:47:59.638 UTC: 	 CRAB Client version: v3.240110
DEBUG 2024-02-21 13:47:59.638 UTC: 	 Running on: Linux login06.hep.wisc.edu 5.4.268-1.el7.elrepo.x86_64 #1 SMP Thu Jan 25 22:44:40 EST 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-02-21 13:47:59.638 UTC: 	 Executing command: 'status'
DEBUG 2024-02-21 13:47:59.639 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
ERROR 2024-02-21 13:47:59.640 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_14_0_0_pre3/src/L1Trigger/L1EGRateStudies/test/crab/crab_20240221_VBFHTT-PU200_13_1X_r1_CMSSW_14_0_0_pre3_GCTJets_calib
ERROR 2024-02-21 13:47:59.640 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 678, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 525, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 519, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_14_0_0_pre3/src/L1Trigger/L1EGRateStudies/test/crab/crab_20240221_VBFHTT-PU200_13_1X_r1_CMSSW_14_0_0_pre3_GCTJets_calib
INFO 2024-02-21 13:47:59.664 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_14_0_0_pre3/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2024-03-20 22:30:46.861 UTC: 	 CRAB Client version: v3.240110
DEBUG 2024-03-20 22:30:46.862 UTC: 	 Running on: Linux login05.hep.wisc.edu 5.4.271-1.el7.elrepo.x86_64 #1 SMP Wed Mar 6 14:47:25 EST 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-03-20 22:30:46.862 UTC: 	 Executing command: 'status'
DEBUG 2024-03-20 22:30:46.862 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
ERROR 2024-03-20 22:30:46.863 UTC: 	 Error: crab_20240319_QCD-PU200_13_1X_r1_CMSSW_14_0_0_pre3_GCTJets_ is not a valid CRAB project directory.
ERROR 2024-03-20 22:30:46.863 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 674, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_20240319_QCD-PU200_13_1X_r1_CMSSW_14_0_0_pre3_GCTJets_ is not a valid CRAB project directory.
INFO 2024-03-20 22:30:46.929 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/CMSSW_14_0_0_pre3/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
DEBUG 2024-07-09 20:38:09.943 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-07-09 20:38:09.944 UTC: 	 Running on: Linux login06.hep.wisc.edu 6.1.92-1.el9.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Sat May 25 13:59:12 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - AlmaLinux 9.4 (Seafoam Ocelot)
DEBUG 2024-07-09 20:38:09.944 UTC: 	 Executing command: 'status'
DEBUG 2024-07-09 20:38:09.944 UTC: 	 Found CRAB cache file /afs/hep.wisc.edu/home/vshang/.crab3
ERROR 2024-07-09 20:38:09.945 UTC: 	 Error: crab_20240626_minBias-PU200_13_1X_r1_CMSSW_14_0_0_pre3_GCTJets_nocalib is not a valid CRAB project directory.
ERROR 2024-07-09 20:38:09.945 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_20240626_minBias-PU200_13_1X_r1_CMSSW_14_0_0_pre3_GCTJets_nocalib is not a valid CRAB project directory.
INFO 2024-07-09 20:38:09.968 UTC: 	 Log file is /afs/hep.wisc.edu/user/vshang/public/Phase2L1CaloTaus/Pallabi/CMSSW_14_0_0_pre3/src/L1Trigger/L1EGRateStudies/test/crab/crab.log
